name: Transient

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - centos-7.8
          - ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ssh qemu curl
    - name: Install transient
      run: |
        sudo pip3 install transient
    - name: Do build
      run: |
        make ${{ matrix.target }}
